# -*- coding: utf-8 -*-

DANGEROUS_PATTERNS = [
    {'name': '强制删除命令', 'regex': r'\brm\s+(-(r\s+f|f\s+r)|-rf|--no-preserve-root)\s+/(etc|bin|lib|usr|var|sys)(/|\b|$)', 'risk_level': 'critical'},
    {'name': '系统目录删除命令', 'regex': r'^\s*rm\s+(-rf\s+|--recursive\s+).*?/(etc|bin|lib|usr|var)(/|$|\s)', 'risk_level': 'critical'},
    {'name': '递归删除命令', 'regex': r'\brm\s+(-(r\s+f|f\s+r)|-rf|--no-preserve-root)\s', 'risk_level': 'critical'},
    {'name': '磁盘覆盖命令', 'regex': r'\bdd\s+.*(if=/dev/.*\bof=/dev/)|(of=/dev/.*\bif=/dev/)', 'risk_level': 'critical'},
    {'name': '磁盘格式化命令', 'regex': r'\bmkfs\.(ext4|xfs|btrfs)\s+/dev/(sd[a-z]|nvme)', 'risk_level': 'critical'},
    {'name': '分区操作命令', 'regex': r'\bfdisk\s+/dev/(sd[a-z]|nvme)', 'risk_level': 'high'},
    {'name': '高危权限修改', 'regex': r'\bchmod\s+([0-7][0-7][0-7][0-7]|777)\s+/(etc|bin|lib|usr)', 'risk_level': 'high'},
    {'name': '系统文件归属修改', 'regex': r'\bchown\s+(-R)?\s+(root|0):(root|0)\s+/(etc|bin|lib|usr)', 'risk_level': 'high'},
    {'name': '黑洞数据清除', 'regex': r'\bmv\s+.*\s+/dev/null\s*$', 'risk_level': 'critical'},
    {'name': '磁盘覆写重定向', 'regex': r'\b.*\s*>&\s*/dev/(sd[a-z]|nvme)', 'risk_level': 'critical'},
    {'name': '系统服务操作', 'regex': r'\bsystemctl\s+(stop|disable|mask)\s+(ssh|network|systemd)', 'risk_level': 'high'},
    {'name': '内核模块卸载', 'regex': r'\brmmod\s+(ext4|xfs|ntfs)', 'risk_level': 'critical'},
    {'name': '危险下载执行', 'regex': r'\b(wget|curl)\s+.*\s*(\||\\)\s*sh\s*$', 'risk_level': 'high'},
    {'name': 'Fork炸弹攻击', 'regex': r'^\s*:$$\{\s*:\|\:&\s*\}\s*;?\s*:\s*', 'risk_level': 'critical'},
    {'name': '系统时间篡改', 'regex': r'\b(date\s+-s\s+["\']|timedatectl\s+set-time\s+)', 'risk_level': 'high'},
    {'name': 'DNS配置修改', 'regex': r'\b(chmod\s+[0-7]{3,4}\s+/etc/resolv\.conf|echo\s+.+\s+>\s*/etc/resolv\.conf)', 'risk_level': 'critical'},
    {'name': '防火墙规则清空', 'regex': r'\b(iptables|ufw)\s+--flush\b', 'risk_level': 'critical'},
    {'name': '端口监听检测', 'regex': r'\bnc\s+-l\s+\d+|socat\s+.*\s+TCP-LISTEN:\d+', 'risk_level': 'high'},
    {'name': 'SSH密钥生成', 'regex': r'\bssh-keygen\s+-t\s+(rsa|ed25519)\s+-f\s+~/(?!\.ssh/id_rsa)', 'risk_level': 'high'},
    {'name': '历史记录窃取', 'regex': r'\b(cat|cp|tar)\s+.*(/root/\.bash_history|/home/[^/]+/\.bash_history)', 'risk_level': 'high'},
    {'name': 'SSH反向隧道', 'regex': r'\bssh\s+-[Rr]\s+\d+:', 'risk_level': 'critical'},
    {'name': 'DNS隐蔽通道', 'regex': r'\b(dig\s+.*\s+@\d+|ncat\s+--udp\s+.*\s+\d+)', 'risk_level': 'high'},
    {'name': '内核参数修改', 'regex': r'\bsysctl\s+-w\s+(net\.ipv4\.ip_forward|kernel\.sysrq)', 'risk_level': 'critical'},
    {'name': '内存擦除', 'regex': r'\b(dd\s+if=/dev/urandom\s+of=/dev/mem|echo\s+1\s+>\s+/proc/sys/kernel/sysrq)', 'risk_level': 'critical'},
    {'name': '交换分区清除', 'regex': r'\bswapoff\s+-a\s+&&\s+dd\s+if=/dev/zero\s+of=/dev/sd[a-z]\d*', 'risk_level': 'critical'},
    {'name': '矿池连接检测', 'regex': r'\b(curl|wget)\s+.*(xmrpool\.eu|nanopool\.org)', 'risk_level': 'critical'},
    {'name': '矿机进程特征', 'regex': r'\b(xmrig|ccminer|minerd)\s+--pool=', 'risk_level': 'critical'},
    {'name': 'Docker高危操作', 'regex': r'\bdocker\s+run\s+.*(--privileged|--cap-add=ALL)', 'risk_level': 'critical'},
    {'name': 'Kubernetes配置篡改', 'regex': r'\bkubectl\s+(create|edit)\s+(configmap|secret)\s+--from-literal=', 'risk_level': 'high'},
    {'name': '日志清除操作', 'regex': r'\b(echo\s+""\s+>\s+/var/log/|journalctl\s+--vacuum-time=)', 'risk_level': 'high'},
    {'name': '审计日志禁用', 'regex': r'\b(auditctl\s+-e\s+0|systemctl\s+stop\s+auditd)', 'risk_level': 'critical'},
    {'name': 'LD_PRELOAD注入', 'regex': r'\bexport\s+LD_PRELOAD=.*\.so', 'risk_level': 'critical'},
    {'name': 'Find高危操作', 'regex': r'\bfind\s+.*\s+-exec\s+.*\s+\;', 'risk_level': 'critical'},
    {'name': 'SSH后门配置', 'regex': r'\b(echo\s+"PermitRootLogin\s+yes"\s+>>\s+/etc/ssh/sshd_config|/usr/sbin/sshd\s+-f\s+/tmp/)', 'risk_level': 'critical'}
]
